[default.general]
chip = "STM32F303VCTx"

[default.reset]
halt_afterwards = true

[default.rtt]
enabled = true
channels = [{ up = 0, down = 0, name = "debug", format = "Defmt" }]

[default.gdb]
enabled = true
